#!/bin/bash
# --------------------------------------------------------------
# Subject:
# Method:
# Author:   2009-02, J.M. Piriou.
# Modifications:
# --------------------------------------------------------------
proc=$(basename $0) # present procedure name.
dirloc=`pwd` # local directory name.
pref=$dirloc/.$proc.tmp.$RANDOM # prefix for tmp files.
dirtmp=$pref.dir # tmp dir name.
#
#-----------------------------------------------
# Execution.
#-----------------------------------------------
#
fe=DHFDLFCST+0024_cy35t1_arome_france_c744
#
#-----------------------------------------------
# Extract domain.
#-----------------------------------------------
#
dom=4
fs=$fe.tmp.domain$dom
ddht -cEXTRAIT_DOMAIN -1$fe -E$dom -s$fs
#
#-----------------------------------------------
# Prognostic budget.
#-----------------------------------------------
#
fe=$fs
budget_package=`basename $dirloc`
for variable in QV CT
do
	ddhb -v $budget_package/$variable -i $fe
done
#
#-----------------------------------------------
# Epilog.
#-----------------------------------------------
#
echo " " ; echo "$proc: end."
#
#-----------------------------------------------
# Cleanings.
#-----------------------------------------------
#
rm -rf $dirtmp
rm -f $pref*
