#!/bin/bash
# --------------------------------------------------------------
# 
# --------------------------------------------------------------
# Sujet:
# Methode:
# Externes:
# Auteur:   2018-07, J.M. Piriou.
# Modifications:
# --------------------------------------------------------------
# En entrée:
# En sortie:
# --------------------------------------------------------------
proc=$(basename $0) # nom de la présente procédure.
pref=`tempo`/$proc.$RANDOM # préfixe des fichiers temporaires.
dirloc=`pwd` # chemin du répertoire local.
#
#-----------------------------------------------
# Traitement de la ligne de commande.
#-----------------------------------------------
#
if [ $# -ne 2 ]
then
  #
  # Mauvais nombre d'arguments.
  #
  echo " "
  echo "OBJET: OBJET: tracé au format PNG de données réelles."
  echo " "
  echo "UTILISATION: $proc FDOC FPNG"
  echo " "
  exit 1
else
  #
  # Nombre d'arguments OK.
  #
  fdoc=$1
  fp=$2
fi
set -evx
#
#-------------------------------------------------
# .
#-------------------------------------------------
#
dd2gr $fdoc $fdoc.svg
convert $fdoc.svg $fp
