#!/bin/bash
# --------------------------------------------------------------
# Subject:
# Method:
# Author:   2009-02, J.M. Piriou.
# Modifications:
# --------------------------------------------------------------
proc=$(basename $0) # present procedure name.
dirloc=`pwd` # local directory name.
pref=$dirloc/.$proc.tmp.$RANDOM # prefix for tmp files.
dirtmp=$pref.dir # tmp dir name.
#
#-----------------------------------------------
# Execution.
#-----------------------------------------------
#
fe=DHFZOh02d+00480.lfa
#
#-----------------------------------------------
# Extract domain.
#-----------------------------------------------
#
fs=$fe.mh
ddhmh $fe $fs
#
#-----------------------------------------------
# Prognostic budget.
#-----------------------------------------------
#
fe=$fs
budget_package=`basename $dirloc`
for variable in QV CT
do
  if [ "$variable" = "QV" ] ; then
    minmax="-n -4. -x 4."
  elif [ "$variable" = "CT" ] ; then
    minmax="-n -3. -x 5."
  else
    minmax=""
  fi
	ddhb -v $budget_package/$variable -i $fe $minmax
done
#
#-----------------------------------------------
# Epilog.
#-----------------------------------------------
#
echo " " ; echo "$proc: end."
#
#-----------------------------------------------
# Cleanings.
#-----------------------------------------------
#
rm -rf $dirtmp
rm -f $pref*
