#!/bin/bash
# --------------------------------------------------------------
#
# --------------------------------------------------------------
# Sujet:
# Methode:
# Externes:
# Auteur:   2024-11-20, J.M. Piriou.
# Modifications:
# --------------------------------------------------------------
# En entrée:
# En sortie:
# --------------------------------------------------------------
proc=$(basename $0) # nom de la présente procédure.
pref=`tempo`/$proc.$RANDOM # préfixe des fichiers temporaires.
dirloc=`pwd` # chemin du répertoire local.
set -evx
#rm -f ddh_presentation_introductive.synctex.gz ddh_synctex.gz
#ote_doubles_points
pdflatex ddh_presentation_introductive.tex
pdflatex ddh_presentation_introductive.tex
v ddh_presentation_introductive.pdf
