#!/bin/bash
# --------------------------------------------------------------
# Bilan de température d'un fichier de DDH-AROME.
# --------------------------------------------------------------
# Sujet:
# Arguments explicites:
# Arguments implicites:
# Methode:
# Externes:
# Auteur:   97-01, J.M. Piriou.
# Modifications:
# --------------------------------------------------------------
# En entree:
# En sortie:
# --------------------------------------------------------------
typb='t' # type de variable dont le bilan est à exécuter.
if [ $# -eq 4 ]
then
	fd=$1     # fichier de DDH.
	reps=$2   # répertoire de sortie.
	ligcad=$3  # ligne de commande additionnelle à ddhi.
	niv_bil=$4 # niveau de bilan à traiter (argument optionnel).
elif [ $# -eq 2 ]
then
	fd=$1     # fichier de DDH.
	reps=$2   # répertoire de sortie.
	ligcad=" "  # ligne de commande additionnelle à ddhi.
	niv_bil="b1" # niveau de bilan à traiter (argument optionnel).
elif [ $# -eq 1 ]
then
	fd=$1     # fichier de DDH.
	reps=`ddhr -i $fd`.tmp.ddhbt # répertoire de sortie.
	ligcad=" "  # ligne de commande additionnelle à ddhi.
	niv_bil="b1" # niveau de bilan à traiter (argument optionnel).
else
	echo " "
	echo "Bilan de température d'un fichier de DDH."
	echo " "
	echo "Utilisation: ddhbt fic_ddh [rep_sor]"
	echo " "
	echo "avec"
	echo "	fic_ddh fichier de ddh d'entrée."
	echo "	rep_sor répertoire des fichiers de sortie; défaut: \$fic_ddh.bilan.tmp"
	echo " "
	exit
fi
ent=`basename $fd` # mnémonique du fichier d'entrée.
#
#-----------------------------------------------
# On crée un répertoire vide.
#-----------------------------------------------
#
rm -rf $reps ; mkdir $reps
#
#-----------------------------------------------
# Copie de sécurité.
#-----------------------------------------------
#
cp $fd $reps/$ent
cd $reps
#
# L'unité utilisée en sortie dépend
# du nombre de niveaux verticaux du fichier de DDH.
#
niv=`ddhr -n $fd` 
if [ "$niv" = "1" ] 
then
	#
	# Un seul niveau dans le fichier DDH.
	#
	coef='-m117.' ; unite='W/m2' # passage K/jour > W/m2.
	#coef=' ' ; unite='K/jour' # K/jour.
else
	#
	# n niveaux dans le fichier DDH.
	#
	coef=' ' ; unite='K/jour' # K/jour.
fi
#
#-----------------------------------------------
# La dynamique des DDH dans le fichier est-elle 
# écrite en tendance ou en divergence de flux?
#-----------------------------------------------
#
typdyn=`lfac $fd DYNAMIQUE`
if [ "$typdyn" = "TENDANCE" ] ; then
	#
	# Tendance.
	#
	TxxDELTAP="#"
else
	#
	# Divergence de flux.
	#
	TxxDELTAP="TCTDELTAP"
fi
#
# Afin de savoir quel type de tracé effectuer,
# et quelles sont les légendes des axes X et Y,
# on fait une interprétation d'un champ,
# et on porte cette information
# sur des variables UNIX locales.
#
cat <<EOF > lc
VUU0
EOF
ddhi $coef $ligcad -e$ent -stmp
format=`grep FORMAT tmp.VUU0.doc`
legendex=`grep LEGENDE_X tmp.VUU0.doc`
legendey=`grep LEGENDE_Y tmp.VUU0.doc`
rm *VUU0*
base=`ddhr -be $ent`
grille=`ddhr -g $ent`
#
if [ "$niv_bil" = "b0" -o "$niv_bil" = "" ]
then
	#
	# Bilan b0 dynamique.
	#
	bilan=b0.$typb.$ent
	sbil=dyn
	cat <<EOF > lc.$bilan.$sbil
VCT0
VCT1
FCTFLUVERTDYN # TEMPERATURE : FLUX VERTICAL DYNAMIQUE                       K/JOUR
$TxxDELTAP
TCTDIVFLUHOR  # TEMPERATURE : DIVERGENCE DES FLUX HORIZONTAUX               K/JOUR
TCTCONVERSI2  # TEMPERATURE : CONVERSION ADIABATIQUE EN POTENT > EN INTERNE K/JOUR
EOF
	ddht -cSEPAR_PR_COMPL -1$ent -s$ent.s -llc.$bilan.$sbil
	cat <<EOF > lc
TCTPRINCIPAL/TEMPERATURE : TENDANCE DYNAMIQUE
EOF
	ddhi $coef $ligcad -e$ent.s -stmp
	mv tmp.TCTPRINCIPAL.dta $bilan.$sbil.dta
	mv tmp.TCTPRINCIPAL.doc $bilan.$sbil.doc
	#
	# Bilan b0 physique.
	#
	bilan=b0.$typb.$ent
	sbil=phys
	cat <<EOF > lc.$bilan.$sbil
VCT0
VCT1
FCTRAYSOL1    # TEMPERATURE : RAYONNEMENT SOLAIRE                           K/JOUR
FCTRAYTER1    # TEMPERATURE : RAYONNEMENT THERMIQUE                         K/JOUR
FCTNEGC1      # TEMPERATURE : NEGC1
FCTDEPI       # TEMPERATURE : VW ADJUSTMENT (DEPI)
FCTVTURB      # TEMPERATURE : TURBULENCE (VTURB)
FCTDISSTUR    # TEMPERATURE : TURBULENCE (DISSTUR)
FCTNEGC       # TEMPERATURE : NEGC
FCTHENUI      # TEMPERATURE : HETEROG. NUCLEATION (HENUI)
FCTHON        # TEMPERATURE : HOMOG. NUCLEATION (HON)
FCTSFR        # TEMPERATURE : SPONTANEOUS FREEZING (SFR)
FCTDEPS       # TEMPERATURE : DEPOSITION ON SNOW (DEPS)
FCTDEPG       # TEMPERATURE : DEPOSITION ON GRAUPEL (DEPG)
FCTREVA       # TEMPERATURE : RAIN EVAPORATION (REVA)
FCTRIM        # TEMPERATURE : RIMING BY CLOUD DROPLETS (RIM)
FCTAGGS       # TEMPERATURE : COLLECTION OF RAIN DROPS (AGGS)
FCTCFRZ       # TEMPERATURE : CONTACT FREEZING (CFRZ)
FCTWETG       # TEMPERATURE : WET GROWTH (WETG)
FCTDRYG       # TEMPERATURE : DRY GROWTH (DRYG)
FCTMLTI       # TEMPERATURE : MELTING OF CLOUD ICE (MLTI)
FCTBERFI      # TEMPERATURE : BERGERON-FINDEISEN EFFECT (BERFI)
EOF
	ddht -cSEPAR_PR_COMPL -1$ent -s$ent.s -llc.$bilan.$sbil
	cat <<EOF > lc
TCTPRINCIPAL/TEMPERATURE : TENDANCE PHYSIQUE
EOF
	ddhi $coef $ligcad -e$ent.s -stmp
	mv tmp.TCTPRINCIPAL.dta $bilan.$sbil.dta
	mv tmp.TCTPRINCIPAL.doc $bilan.$sbil.doc
	#
	# Bilan b0 VCTM.
	#
	bilan=b0.$typb.$ent
	sbil=tendance
	cat <<EOF > lc
VCTM
EOF
	ddhi $coef $ligcad -e$ent
	mv $ent.tmp.VCTM.dta $bilan.$sbil.dta
	mv $ent.tmp.VCTM.doc $bilan.$sbil.doc
	#
	# Bilan b0 résidu.
	#
	bilan=b0.$typb.$ent
	sbil=residu
	cat <<EOF > lc.$bilan.$sbil
VCT0
VCT1
FCTFLUVERTDYN # TEMPERATURE : FLUX VERTICAL DYNAMIQUE                       K/JOUR
$TxxDELTAP
TCTDIVFLUHOR  # TEMPERATURE : DIVERGENCE DES FLUX HORIZONTAUX               K/JOUR
TCTCONVERSI2  # TEMPERATURE : CONVERSION ADIABATIQUE EN POTENT > EN INTERNE K/JOUR
FCTRAYSOL1    # TEMPERATURE : RAYONNEMENT SOLAIRE                           K/JOUR
FCTRAYTER1    # TEMPERATURE : RAYONNEMENT THERMIQUE                         K/JOUR
FCTNEGC1      # TEMPERATURE : NEGC1
FCTDEPI       # TEMPERATURE : VW ADJUSTMENT (DEPI)
FCTVTURB      # TEMPERATURE : TURBULENCE (VTURB)
FCTDISSTUR    # TEMPERATURE : TURBULENCE (DISSTUR)
FCTNEGC       # TEMPERATURE : NEGC
FCTHENUI      # TEMPERATURE : HETEROG. NUCLEATION (HENUI)
FCTHON        # TEMPERATURE : HOMOG. NUCLEATION (HON)
FCTSFR        # TEMPERATURE : SPONTANEOUS FREEZING (SFR)
FCTDEPS       # TEMPERATURE : DEPOSITION ON SNOW (DEPS)
FCTDEPG       # TEMPERATURE : DEPOSITION ON GRAUPEL (DEPG)
FCTREVA       # TEMPERATURE : RAIN EVAPORATION (REVA)
FCTRIM        # TEMPERATURE : RIMING BY CLOUD DROPLETS (RIM)
FCTAGGS       # TEMPERATURE : COLLECTION OF RAIN DROPS (AGGS)
FCTCFRZ       # TEMPERATURE : CONTACT FREEZING (CFRZ)
FCTWETG       # TEMPERATURE : WET GROWTH (WETG)
FCTDRYG       # TEMPERATURE : DRY GROWTH (DRYG)
FCTMLTI       # TEMPERATURE : MELTING OF CLOUD ICE (MLTI)
FCTBERFI      # TEMPERATURE : BERGERON-FINDEISEN EFFECT (BERFI)
EOF
	ddht -cSEPAR_PR_COMPL -1$ent -s$ent.s -llc.$bilan.$sbil
	cat <<EOF > lc
TCTCOMPLEMENT/TEMPERATURE : RESIDU
EOF
	ddhi $coef $ligcad -e$ent.s -stmp
	mv tmp.TCTCOMPLEMENT.dta $bilan.$sbil.dta
	mv tmp.TCTCOMPLEMENT.doc $bilan.$sbil.doc
	#
	# On crée un fichier ".doc" en vue du tracé documenté.
	#
	origine=`ddhr -i $ent`" - "$ent
	cat <<EOF > z$bilan.doc
${format}I
#TITRE=Bilan de température
#DATE=$base
#UNITE=$unite
#ORIGINE=$origine
#GRILLE=$grille
$legendex
$legendey
#MIN=
#MAX=
#MOY=
#ECT=
#RCM=
#VREF=0.
EOF
	for dta in $bilan.*.dta
	do
	nom_en_clair=`mot 7 -2 $dta`
	cat <<EOF >> z$bilan.doc
#CHAMP=$nom_en_clair
#FICHIER=$dta
EOF
	done
fi
if [ "$niv_bil" = "b1" -o "$niv_bil" = "" ]
then
	#
	# Bilan b1 dyn.
	#
	bilan=b1.$typb.$ent
	sbil=dyn
	cat <<EOF > lc.$bilan.$sbil
VCT0
VCT1
FCTFLUVERTDYN # TEMPERATURE : FLUX VERTICAL DYNAMIQUE                       K/JOUR
$TxxDELTAP
TCTDIVFLUHOR  # TEMPERATURE : DIVERGENCE DES FLUX HORIZONTAUX               K/JOUR
TCTCONVERSI2  # TEMPERATURE : CONVERSION ADIABATIQUE EN POTENT > EN INTERNE K/JOUR
EOF
	ddht -cSEPAR_PR_COMPL -1$ent -s$ent.s -llc.$bilan.$sbil
	cat <<EOF > lc
TCTPRINCIPAL/TEMPERATURE : TENDANCE DYNAMIQUE
EOF
	ddhi $coef $ligcad -e$ent.s -stmp
	mv tmp.TCTPRINCIPAL.dta $bilan.$sbil.dta
	mv tmp.TCTPRINCIPAL.doc $bilan.$sbil.doc
	#
	# Bilan b1 microphysique.
	#
	bilan=b1.$typb.$ent
	sbil=microphysique
	cat <<EOF > lc.$bilan.$sbil
VCT0
VCT1
FCTDEPI       # TEMPERATURE : VW ADJUSTMENT (DEPI)
FCTNEGC1      # TEMPERATURE : NEGC1
FCTNEGC       # TEMPERATURE : NEGC
FCTHENUI      # TEMPERATURE : HETEROG. NUCLEATION (HENUI)
FCTHON        # TEMPERATURE : HOMOG. NUCLEATION (HON)
FCTSFR        # TEMPERATURE : SPONTANEOUS FREEZING (SFR)
FCTDEPS       # TEMPERATURE : DEPOSITION ON SNOW (DEPS)
FCTDEPG       # TEMPERATURE : DEPOSITION ON GRAUPEL (DEPG)
FCTREVA       # TEMPERATURE : RAIN EVAPORATION (REVA)
FCTRIM        # TEMPERATURE : RIMING BY CLOUD DROPLETS (RIM)
FCTAGGS       # TEMPERATURE : COLLECTION OF RAIN DROPS (AGGS)
FCTCFRZ       # TEMPERATURE : CONTACT FREEZING (CFRZ)
FCTWETG       # TEMPERATURE : WET GROWTH (WETG)
FCTDRYG       # TEMPERATURE : DRY GROWTH (DRYG)
FCTMLTI       # TEMPERATURE : MELTING OF CLOUD ICE (MLTI)
FCTBERFI      # TEMPERATURE : BERGERON-FINDEISEN EFFECT (BERFI)
EOF
	ddht -cSEPAR_PR_COMPL -1$ent -s$ent.s -llc.$bilan.$sbil
	cat <<EOF > lc
TCTPRINCIPAL/ TEMPERATURE : MICROPHYSIQUE
EOF
	ddhi $coef $ligcad -e$ent.s -stmp
	mv tmp.TCTPRINCIPAL.dta $bilan.$sbil.dta
	mv tmp.TCTPRINCIPAL.doc $bilan.$sbil.doc
	#
	# Bilan b1 ray_sol.
	#
	bilan=b1.$typb.$ent
	sbil=ray_sol
	cat <<EOF > lc.$bilan.$sbil
VCT0
VCT1
FCTRAYSOL1    # TEMPERATURE : RAYONNEMENT SOLAIRE                           K/JOUR
EOF
	ddht -cSEPAR_PR_COMPL -1$ent -s$ent.s -llc.$bilan.$sbil
	cat <<EOF > lc
TCTPRINCIPAL/TEMPERATURE : RAYONNEMENT SOLAIRE
EOF
	ddhi $coef $ligcad -e$ent.s -stmp
	mv tmp.TCTPRINCIPAL.dta $bilan.$sbil.dta
	mv tmp.TCTPRINCIPAL.doc $bilan.$sbil.doc
	#
	# Bilan b1 ray_ther.
	#
	bilan=b1.$typb.$ent
	sbil=ray_ther
	cat <<EOF > lc.$bilan.$sbil
VCT0
VCT1
FCTRAYTER1    # TEMPERATURE : RAYONNEMENT THERMIQUE                         K/JOUR
EOF
	ddht -cSEPAR_PR_COMPL -1$ent -s$ent.s -llc.$bilan.$sbil
	cat <<EOF > lc
TCTPRINCIPAL/TEMPERATURE : RAYONNEMENT THERMIQUE
EOF
	ddhi $coef $ligcad -e$ent.s -stmp
	mv tmp.TCTPRINCIPAL.dta $bilan.$sbil.dta
	mv tmp.TCTPRINCIPAL.doc $bilan.$sbil.doc
	#
	# Bilan b1 tur.
	#
	bilan=b1.$typb.$ent
	sbil=tur
	cat <<EOF > lc.$bilan.$sbil
VCT0
VCT1
FCTVTURB      # TEMPERATURE : TURBULENCE (VTURB)
FCTDISSTUR    # TEMPERATURE : TURBULENCE (DISSTUR)
EOF
	ddht -cSEPAR_PR_COMPL -1$ent -s$ent.s -llc.$bilan.$sbil
	cat <<EOF > lc
TCTPRINCIPAL/TEMPERATURE : TURB. SECHE+CVPP+CVP
EOF
	ddhi $coef $ligcad -e$ent.s -stmp
	mv tmp.TCTPRINCIPAL.dta $bilan.$sbil.dta
	mv tmp.TCTPRINCIPAL.doc $bilan.$sbil.doc
	#
	# Bilan b1 VCTM.
	#
	bilan=b1.$typb.$ent
	sbil=tendance
	cat <<EOF > lc
VCTM
EOF
	ddhi $coef $ligcad -e$ent
	mv $ent.tmp.VCTM.dta $bilan.$sbil.dta
	mv $ent.tmp.VCTM.doc $bilan.$sbil.doc
	#
	# Bilan b1 résidu.
	#
	bilan=b1.$typb.$ent
	sbil=residu
	cat <<EOF > lc.$bilan.$sbil
VCT0
VCT1
FCTFLUVERTDYN # TEMPERATURE : FLUX VERTICAL DYNAMIQUE                       K/JOUR
$TxxDELTAP
TCTDIVFLUHOR  # TEMPERATURE : DIVERGENCE DES FLUX HORIZONTAUX               K/JOUR
TCTCONVERSI2  # TEMPERATURE : CONVERSION ADIABATIQUE EN POTENT > EN INTERNE K/JOUR
FCTRAYSOL1    # TEMPERATURE : RAYONNEMENT SOLAIRE                           K/JOUR
FCTRAYTER1    # TEMPERATURE : RAYONNEMENT THERMIQUE                         K/JOUR
FCTNEGC1      # TEMPERATURE : NEGC1
FCTDEPI       # TEMPERATURE : VW ADJUSTMENT (DEPI)
FCTVTURB      # TEMPERATURE : TURBULENCE (VTURB)
FCTDISSTUR    # TEMPERATURE : TURBULENCE (DISSTUR)
FCTNEGC       # TEMPERATURE : NEGC
FCTHENUI      # TEMPERATURE : HETEROG. NUCLEATION (HENUI)
FCTHON        # TEMPERATURE : HOMOG. NUCLEATION (HON)
FCTSFR        # TEMPERATURE : SPONTANEOUS FREEZING (SFR)
FCTDEPS       # TEMPERATURE : DEPOSITION ON SNOW (DEPS)
FCTDEPG       # TEMPERATURE : DEPOSITION ON GRAUPEL (DEPG)
FCTREVA       # TEMPERATURE : RAIN EVAPORATION (REVA)
FCTRIM        # TEMPERATURE : RIMING BY CLOUD DROPLETS (RIM)
FCTAGGS       # TEMPERATURE : COLLECTION OF RAIN DROPS (AGGS)
FCTCFRZ       # TEMPERATURE : CONTACT FREEZING (CFRZ)
FCTWETG       # TEMPERATURE : WET GROWTH (WETG)
FCTDRYG       # TEMPERATURE : DRY GROWTH (DRYG)
FCTMLTI       # TEMPERATURE : MELTING OF CLOUD ICE (MLTI)
FCTBERFI      # TEMPERATURE : BERGERON-FINDEISEN EFFECT (BERFI)
EOF
	ddht -cSEPAR_PR_COMPL -1$ent -s$ent.s -llc.$bilan.$sbil
	cat <<EOF > lc
TCTCOMPLEMENT/TEMPERATURE : RESIDU
EOF
	ddhi $coef $ligcad -e$ent.s -stmp
	mv tmp.TCTCOMPLEMENT.dta $bilan.$sbil.dta
	mv tmp.TCTCOMPLEMENT.doc $bilan.$sbil.doc
	#
	# On crée un fichier ".doc" en vue du tracé documenté.
	#
	origine=`ddhr -i $ent`" - "$ent
	cat <<EOF > z$bilan.doc
${format}I
#TITRE=Bilan de température
#DATE=$base
#UNITE=$unite
#ORIGINE=$origine
#GRILLE=$grille
$legendex
$legendey
#MIN=
#MAX=
#MOY=
#ECT=
#RCM=
#VREF=0.
EOF
	for dta in $bilan.*.dta
	do
	nom_en_clair=`mot 7 -2 $dta`
	cat <<EOF >> z$bilan.doc
#CHAMP=$nom_en_clair
#FICHIER=$dta
EOF
	done
fi
if [ "$niv_bil" = "b2" -o "$niv_bil" = "" ]
then
	#
	# Bilan b2: détail maximal.
	#
	bilan=b2.$typb.$ent
	cat <<EOF > lc
VCTM
FCTFLUVERTDYN # TEMPERATURE : FLUX VERTICAL DYNAMIQUE                       K/JOUR
$TxxDELTAP
TCTDIVFLUHOR  # TEMPERATURE : DIVERGENCE DES FLUX HORIZONTAUX               K/JOUR
TCTCONVERSI2  # TEMPERATURE : CONVERSION ADIABATIQUE EN POTENT > EN INTERNE K/JOUR
FCTRAYSOL1    # TEMPERATURE : RAYONNEMENT SOLAIRE                           K/JOUR
FCTRAYTER1    # TEMPERATURE : RAYONNEMENT THERMIQUE                         K/JOUR
FCTNEGC1      # TEMPERATURE : NEGC1
FCTDEPI       # TEMPERATURE : VW ADJUSTMENT (DEPI)
FCTVTURB      # TEMPERATURE : TURBULENCE (VTURB)
FCTDISSTUR    # TEMPERATURE : TURBULENCE (DISSTUR)
FCTNEGC       # TEMPERATURE : NEGC
FCTHENUI      # TEMPERATURE : HETEROG. NUCLEATION (HENUI)
FCTHON        # TEMPERATURE : HOMOG. NUCLEATION (HON)
FCTSFR        # TEMPERATURE : SPONTANEOUS FREEZING (SFR)
FCTDEPS       # TEMPERATURE : DEPOSITION ON SNOW (DEPS)
FCTDEPG       # TEMPERATURE : DEPOSITION ON GRAUPEL (DEPG)
FCTREVA       # TEMPERATURE : RAIN EVAPORATION (REVA)
FCTRIM        # TEMPERATURE : RIMING BY CLOUD DROPLETS (RIM)
FCTAGGS       # TEMPERATURE : COLLECTION OF RAIN DROPS (AGGS)
FCTCFRZ       # TEMPERATURE : CONTACT FREEZING (CFRZ)
FCTWETG       # TEMPERATURE : WET GROWTH (WETG)
FCTDRYG       # TEMPERATURE : DRY GROWTH (DRYG)
FCTMLTI       # TEMPERATURE : MELTING OF CLOUD ICE (MLTI)
FCTBERFI      # TEMPERATURE : BERGERON-FINDEISEN EFFECT (BERFI)
EOF
	ddhi $coef $ligcad -e$ent -s$bilan
	#
	# Bilan b2: résidu.
	#
	bilan=b2.$typb.$ent
	sbil=residu
	cat <<EOF > lc
VCT0
VCT1
FCTFLUVERTDYN # TEMPERATURE : FLUX VERTICAL DYNAMIQUE                       K/JOUR
$TxxDELTAP
TCTDIVFLUHOR  # TEMPERATURE : DIVERGENCE DES FLUX HORIZONTAUX               K/JOUR
TCTCONVERSI2  # TEMPERATURE : CONVERSION ADIABATIQUE EN POTENT > EN INTERNE K/JOUR
FCTRAYSOL1    # TEMPERATURE : RAYONNEMENT SOLAIRE                           K/JOUR
FCTRAYTER1    # TEMPERATURE : RAYONNEMENT THERMIQUE                         K/JOUR
FCTNEGC1      # TEMPERATURE : NEGC1
FCTDEPI       # TEMPERATURE : VW ADJUSTMENT (DEPI)
FCTVTURB      # TEMPERATURE : TURBULENCE (VTURB)
FCTDISSTUR    # TEMPERATURE : TURBULENCE (DISSTUR)
FCTNEGC       # TEMPERATURE : NEGC
FCTHENUI      # TEMPERATURE : HETEROG. NUCLEATION (HENUI)
FCTHON        # TEMPERATURE : HOMOG. NUCLEATION (HON)
FCTSFR        # TEMPERATURE : SPONTANEOUS FREEZING (SFR)
FCTDEPS       # TEMPERATURE : DEPOSITION ON SNOW (DEPS)
FCTDEPG       # TEMPERATURE : DEPOSITION ON GRAUPEL (DEPG)
FCTREVA       # TEMPERATURE : RAIN EVAPORATION (REVA)
FCTRIM        # TEMPERATURE : RIMING BY CLOUD DROPLETS (RIM)
FCTAGGS       # TEMPERATURE : COLLECTION OF RAIN DROPS (AGGS)
FCTCFRZ       # TEMPERATURE : CONTACT FREEZING (CFRZ)
FCTWETG       # TEMPERATURE : WET GROWTH (WETG)
FCTDRYG       # TEMPERATURE : DRY GROWTH (DRYG)
FCTMLTI       # TEMPERATURE : MELTING OF CLOUD ICE (MLTI)
FCTBERFI      # TEMPERATURE : BERGERON-FINDEISEN EFFECT (BERFI)
EOF
	ddht -cSEPAR_PR_COMPL -1$ent -s$ent.s -llc
	cat <<EOF > lc
TCTCOMPLEMENT/TEMPERATURE : RESIDU
EOF
	ddhi $coef $ligcad -e$ent.s -stmp
	mv tmp.TCTCOMPLEMENT.dta $bilan.$sbil.dta
	mv tmp.TCTCOMPLEMENT.doc $bilan.$sbil.doc
	#
	# On crée un fichier ".doc" en vue du tracé documenté.
	#
	origine=`ddhr -i $ent`" - "$ent
	cat <<EOF > z$bilan.doc
${format}I
#TITRE=Bilan de température
#DATE=$base
#UNITE=$unite
#ORIGINE=$origine
#GRILLE=$grille
$legendex
$legendey
#MIN=
#MAX=
#MOY=
#ECT=
#RCM=
#VREF=0.
EOF
	for dta in $bilan.*.dta
	do
	nom_en_clair=`mot 7 -2 $dta`
	cat <<EOF >> z$bilan.doc
#CHAMP=$nom_en_clair
#FICHIER=$dta
EOF
	done
fi
cd .. ; ls -lrt
