#!/bin/bash
# --------------------------------------------------------------
# 
# --------------------------------------------------------------
# Sujet:
# Methode:
# Externes:
# Auteur:   2006-04, J.M. Piriou.
# Modifications:
# --------------------------------------------------------------
# En entrée:
# En sortie:
# --------------------------------------------------------------
proc=$(basename $0) # nom de la présente procédure.
dirloc=`pwd` # chemin du répertoire local.
pref=$dirloc/.$proc.tmp.$RANDOM # préfixe des fichiers temporaires.
#
#-----------------------------------------------
# Traitement de la ligne de commande.
#-----------------------------------------------
#
if [ $# -lt 4 ]
then
	#
	# Mauvais nombre d'arguments.
	#
	echo " "
	echo "OBJET: alimentation de la base de données intranet en données de DDH."
	echo " "
	echo "UTILISATION: $proc [-d AAAAMMQQ] -c CHAINE -hv VV -dp DD -s SITE1 [SITE2 ... SITEn]"
	echo "	Si la date n'est pas fournie, le défaut est la date du jour."
	echo "	CHAINE est la chaîne ayant produit les fichiers de DDH; exemple: ARPEGE_oper, ARPEGE_double, AROME_MIDPYR, etc."
	echo "	VV est l'heure UTC de validité de la prévision."
	echo "	DD est la durée de prévision en heures."
	echo "	SITE1 [SITE2 ... SITEn] est la liste des sites, chacun étant donné au format -000.692_+44.832_Bordeaux."
	echo " "
	echo "METHODE: "
	echo "	Si on appelle J la date AAAAMMQQ, $proc extrait depuis archive les profils DDH prévus par la chaîne CHAINE,"
	echo "	valides le jour J à l'heure UTC VV, issus d'une prévision de durée DD."
	echo "	Ces profils prévus sont convertis en fichiers type M1D, puis copiés sur un répertoire intranet préétabli,"
	echo "	écrit en dur dans le présent script."
	echo " "
	echo "EXEMPLE1: $proc -c ARPEGE_oper -hv 24 -dp 48 -s -000.692_+44.832_Bordeaux +001.374_+43.575_Toulouse-Meteopole +004.407_+43.858_Nimes"
	echo "	Pour la prévision ARPEGE oper valide à 24h UTC le jour-même, issue d'une prévision à 24h, sur les sites de Bordeaux, Toulouse-Meteopole et Nîmes."
	echo "EXEMPLE2: $proc -c AROME_MIDPYR -hv 12 -dp 12 -s -000.692_+44.832_Bordeaux +004.407_+43.858_Nimes"
	echo "	Pour la prévision AROME midi-pyrénées valide à 12h UTC le jour-même, issue d'une prévision à 12h, sur les sites de Bordeaux et Nîmes."
	echo " "
	exit
fi
#
#-----------------------------------------------
# Obtention de la date depuis la ligne de commande.
#-----------------------------------------------
#
if [ "$1" = "-d" ] ; then
	shift
	aaaammqq=$1
	shift
else
	aaaammqq=`datecou -date`
fi
#
#-----------------------------------------------
# Obtention de la chaîne depuis la ligne de commande.
#-----------------------------------------------
#
if [ "$1" = "-c" ] ; then
	shift
	exp=$1
	shift
else
	echo " "
	echo "$proc/ERREUR: argument -c attendu, or absent de la ligne de commande!..."
	echo " "
	exit
fi
#
#-----------------------------------------------
# Obtention de l'heure de validité depuis la ligne de commande.
#-----------------------------------------------
#
if [ "$1" = "-hv" ] ; then
	shift
	hv=$1
	shift
else
	echo " "
	echo "$proc/ERREUR: argument -hv attendu, or absent de la ligne de commande!..."
	echo " "
	exit
fi
#
#-----------------------------------------------
# Obtention de la durée de prévision depuis la ligne de commande.
#-----------------------------------------------
#
if [ "$1" = "-dp" ] ; then
	shift
	dp=$1
	shift
else
	echo " "
	echo "$proc/ERREUR: argument -dp attendu, or absent de la ligne de commande!..."
	echo " "
	exit
fi
#
#-----------------------------------------------
# Obtention des sites depuis la ligne de commande.
#-----------------------------------------------
#
if [ "$1" = "-s" ] ; then
	shift
	sites=$*
else
	echo " "
	echo "$proc/ERREUR: argument -s attendu, or absent de la ligne de commande!..."
	echo " "
	exit
fi
#
#-----------------------------------------------
# Exécution.
#-----------------------------------------------
#
#
#-----------------------------------------------
# Création du répertoire de travail temporaire.
#-----------------------------------------------
#
reptmp=$dirloc/.$proc.`datecou`.tmp.$RANDOM ; rm -rf $reptmp ; mkdir $reptmp
cd $reptmp
#
#-----------------------------------------------
# Base de la prévision.
#-----------------------------------------------
#
#
# La base est égale à aaaammqq à hv heures UTC moins dp heures de prévision.
# base_run ci-dessous sera ua format AAAAMMQQHH.
#
base_run=`cals -fi10 "$aaaammqq g-j $hv $dp - 24 / + j-g s frc 24 * nint r int 100 * +"`
aaaammqq_base_run=`expr $base_run | cut -c1-8`
hh_base_run=`expr $base_run | cut -c9-10`
if [ "$hh_base_run" = "00" ] ; then
	reseau_base_run="r0"
elif [ "$hh_base_run" = "12" ] ; then
	reseau_base_run="r12"
else
	echo " "
	echo "$proc/ERREUR: Compte-tenu de l'heure de validité et de la durée de prévision!..."
	echo " "
	exit
fi
#
#-----------------------------------------------
# Obtention du fichier-tar de DDH.
#-----------------------------------------------
#
cible="dhfcloudnet.tar"
rm -f $cible DHF*
ftgetp_ddhtar $exp $aaaammqq_base_run $reseau_base_run $cible
if test -s $cible
then
	tar xf $cible
	#
	#-----------------------------------------------
	# On ne s'intéresse qu'à la prévision de durée dp heures.
	#-----------------------------------------------
	#
	rm -f ddh.lfa
	cp DHF*00${dp} ddh.lfa
	if test ! -s ddh.lfa
	then
		echo " "
		echo "$proc/ERREUR: le fichier tar $exp $aaaammqq_base_run $reseau_base_run ne contient pas l'échéance $dp!..."
		echo " "
		exit
	fi
	rm DHF*
	#
	#-----------------------------------------------
	# Boucle sur les sites.
	#-----------------------------------------------
	#
	for site in $sites 
	do
		#
		#-----------------------------------------------
		# Extraction du domaine DDH.
		#-----------------------------------------------
		#
		rm -f ddh.lfa.dom
		ddht -cEXTRAIT_DOMAIN -E$site -1ddh.lfa -sddh.lfa.dom
		ddh2scm ddh.lfa.dom
		#
		#-----------------------------------------------
		# Nom en clair du site de RS.
		#-----------------------------------------------
		#
		nomc=`echo $site | cut -d "_" -f3`
		#
		#-----------------------------------------------
		# Copie des fichiers de DDH et type M1D sur les répertoires WEB.
		#-----------------------------------------------
		#
		reps=$HOME/html/NO_SAVE/profils_sites_de_rs/$nomc/$aaaammqq-$hv
		mkdir -p $reps
		cp ddh.lfa.dom.Dom001.Var_fin.scm $reps/$exp.lfa
		echo " " ; echo "$proc: création du fichier M1D $reps/$exp.lfa"
	done
fi
#
#-----------------------------------------------
# Epilogue.
#-----------------------------------------------
#
echo " " ; echo "$proc: fin."
#
#-----------------------------------------------
# Nettoyage.
#-----------------------------------------------
#
rm -f $pref* 
rm -rf $reptmp
