#!/bin/bash
# --------------------------------------------------------------
# 
# --------------------------------------------------------------
# Sujet:
# Methode:
# Externes:
# Auteur:   2003-12, J.M. Piriou.
# Modifications:
#           2015-05, J.M. Piriou: interpolation avant combinaison par ddhif.
# --------------------------------------------------------------
# En entrée:
# En sortie:
# --------------------------------------------------------------
proc=$(basename $0) # nom de la présente procédure.
pref=`tempo`/$proc.$RANDOM # préfixe des fichiers temporaires.
dirloc=`pwd` # chemin du répertoire local.
#
#-----------------------------------------------
# Traitement de la ligne de commande.
#-----------------------------------------------
#
if [ $# -eq 3 ]
then
	#
	# Nombre d'arguments OK.
	#
	aaaa=$1
	mm=$2
  chaine=$3
else
	#
	# Mauvais nombre d'arguments.
	#
	echo " "
	echo "OBJET: crée le fichier DDH contenant la tendance entre les analyses du mois."
	echo " "
	echo "UTILISATION: $proc ANNEE MOIS chaîne"
	echo "avec chaîne=OPER ou DBLE "
	echo " "
	exit
fi
set -evx
cible=$HOME/dev/ddh/cumuls_mensuels_$chaine/$aaaa/$mm
mkdir -p $cible
fs=$cible/dhfzoana+1mois.lfa
#
#-----------------------------------------------
# Fichier-analyse du 1er du mois de MM.
#-----------------------------------------------
#
echo "Fichier-analyse du 1er du mois de MM"
fmm0=$pref.debut_mois.lfa
rm -f $fmm0
#
#-----------------------------------------------
# Fichier-analyse du 1er du mois de MM+1.
#-----------------------------------------------
#
echo "Fichier-analyse du 1er du mois de MM+1"
#
# On sort dans aaaamm1 l'AAAAMM du mois suivant.
#
aaaamm1=`cals -fi6 "$aaaa $mm X<>Y 100 * + 100 * 15 + 30 DATE+ 100 / INT"`
aaaa1=`expr $aaaamm1 | cut -c1-4`
mm1=`expr $aaaamm1 | cut -c5-6`
fdate1=$aaaa1.$mm1
fmm1=$pref.fin_mois.lfa 
rm -f $fmm1
if [ "$chaine" = "OPER" -o "$chaine" = "DBLE" ] ; then
  #
  #-------------------------------------------------
  # Début de mois.
  #-------------------------------------------------
  #
  ftgetp ~mxpt001/vortex/arpege/4dvarfr/$chaine/${aaaa}/${mm}/01/T0000P/forecast/ddh.arpege-zonal.tl1798-c22.ddhpack.tgz DHFZOARPE.tgz
  tar xvf DHFZOARPE.tgz
  mv HIDDEN.${aaaa}${mm}*/DHFZOFCST+0072 $fmm0
  rm -rf DHFZOARPE.tgz HIDDEN.${aaaa}${mm}*
  #
  #-------------------------------------------------
  # Début de mois suivant.
  #-------------------------------------------------
  #
  ftgetp ~mxpt001/vortex/arpege/4dvarfr/$chaine/${aaaa1}/${mm1}/01/T0000P/forecast/ddh.arpege-zonal.tl1798-c22.ddhpack.tgz DHFZOARPE.tgz
  tar xvf DHFZOARPE.tgz
  mv HIDDEN.${aaaa1}${mm1}*/DHFZOFCST+0072 $fmm1
  rm -rf DHFZOARPE.tgz HIDDEN.${aaaa1}${mm1}*
else
  c1=`expr $chaine | cut -c1-1`
  c2=`expr $chaine | cut -c2-2`
  c3=`expr $chaine | cut -c3-3`
  c4=`expr $chaine | cut -c4-4`
  #
  #-------------------------------------------------
  # Début de mois.
  #-------------------------------------------------
  #
  ftgetp /home/m/marp/marp999/vortex/arpege/4dvarfr/$c1/$c2/$c3/$c4/${aaaa}${mm}01T0000P/forecast/ddh.arpege-zonal.tl1798-c22.ddhpack.tgz DHFZOARPE.tgz
  tar xvf DHFZOARPE.tgz
  mv ddhpack_zonal/DHFZOFCST+0072 $fmm0
  rm -rf DHFZOARPE.tgz ddhpack_zonal
  #
  #-------------------------------------------------
  # Début de mois suivant.
  #-------------------------------------------------
  #
  ftgetp /home/m/marp/marp999/vortex/arpege/4dvarfr/$c1/$c2/$c3/$c4/${aaaa1}${mm1}01T0000P/forecast/ddh.arpege-zonal.tl1798-c22.ddhpack.tgz DHFZOARPE.tgz
  tar xvf DHFZOARPE.tgz
  mv ddhpack_zonal/DHFZOFCST+0072 $fmm1
  rm -rf DHFZOARPE.tgz ddhpack_zonal
fi
#
#-----------------------------------------------
# Test d'existence du fichier avant de continuer le travail.
#-----------------------------------------------
#
ftest=$fmm1
if test ! -s $ftest
then
	echo " "
	echo "$proc/ERREUR: le fichier $ftest est absent!..."
	echo " "
	exit
fi
#
#-----------------------------------------------
# On va dans le répertoire de sortie.
#-----------------------------------------------
#
cd $cible
#
#-------------------------------------------------
# Interpolation éventuelle du premier fichier sur la grille du second.
#-------------------------------------------------
#
ddh_interpole $fmm0 $fmm1 $pref.grille1.lfa
#
#-----------------------------------------------
# Nombre de jours entre le 1er du mois et le 1er du mois suivant.
#-----------------------------------------------
#
nbj=`cals -fi2.2 "$aaaa 10000 * $mm 100 * + 1 + $aaaa1 10000 * $mm1 100 * + 1 + DDAYS"`
echo " "
echo "$nbj jours durant le mois $mm de l'année $aaaa"
exe="ddhif $pref.grille1.lfa $fmm1 $nbj $fs"
echo $exe
$exe
ddhindexp $chaine $fs
