#!/bin/bash
# --------------------------------------------------------------
# 
# --------------------------------------------------------------
# Sujet:
# Methode:
# Externes:
# Auteur:   2000-02, J.M. Piriou.
# Modifications:
# --------------------------------------------------------------
# En entrée:
# En sortie:
# --------------------------------------------------------------
proc=$(basename $0) # nom de la présente procédure.
pref=`tempo`/$proc.$RANDOM # préfixe des fichiers temporaires.
dirloc=`pwd` # chemin du répertoire local.
#
#-----------------------------------------------
# Traitement de la ligne de commande.
#-----------------------------------------------
#
if [ $# -le 3 ]
then
	#
	# Mauvais nombre d'arguments.
	#
	echo " "
	echo "OBJET: étude d'évolution d'un champ DDH sur n fichiers."
	echo " "
	echo "UTILISATION: $proc CHAMP FIC1 ... FICn"
	echo " "
	echo "EXEMPLE: $proc VCTM D*lfa"
	echo " "
	exit
else
	champ=$1 ; shift
fi
#
#-----------------------------------------------
# Répertoire de sortie.
#-----------------------------------------------
#
reps=$proc.$champ.$RANDOM.tmp
rm -rf $reps ; mkdir $reps
#
#-----------------------------------------------
# Exécution.
#-----------------------------------------------
#
for f in $*
do
	#
	#-----------------------------------------------
	# On se place dans le répertoire d'appel.
	#-----------------------------------------------
	#
	cd $dirloc
	#
	#-----------------------------------------------
	# Copie locale.
	#-----------------------------------------------
	#
	fe=$f
	#fs=$reps/`basename $fe` ; cp $fe $fs ; fe=$fs
	fs=$reps/E`ddhr -eh $fe`.lfa ; cp $fe $fs ; fe=$fs
	#
	#-----------------------------------------------
	# On se place dans le répertoire cible.
	#-----------------------------------------------
	#
	cd $reps
	fe=`basename $fe`
	#
	#-----------------------------------------------
	# Extraction de domaines.
	#-----------------------------------------------
	#
	#dom="8-19" ; fs=$fe.dom$dom ; ddht -cEXTRAIT_DOMAIN -E$dom -1$fe -s$fs ; fe=$fs
	#
	#-----------------------------------------------
	# Moyenne horizontale.
	#-----------------------------------------------
	#
	#fs=$fe.mh ; ddhmh $fe $fs ; fe=$fs
	#
	#-----------------------------------------------
	# Moyenne verticale.
	#-----------------------------------------------
	#
	#fs=$fe.mv ; ddhmv $fe $fs ; fe=$fs
	#
	#-----------------------------------------------
	# Moyenne globale.
	#-----------------------------------------------
	#
	#fs=$fe.mg ; ddhmg $fe $fs ; fe=$fs
	#
	#-----------------------------------------------
	# Interprétation.
	#-----------------------------------------------
	#
	#ddh_prec $fe
	#
	#-----------------------------------------------
	# Liste des champs. On peut en mettre plusieurs.
	#-----------------------------------------------
	#
	echo $champ > lc
	ddhi $fe
	#
	#-----------------------------------------------
	# Bilan.
	#-----------------------------------------------
	#
	#ddhbqv $fe $fe.bilan ' ' b1
	#cd $fe.bilan ; dd2eps z*.doc ; mv *.eps ../$fe.eps ; convert ../$fe.eps ../$fe.eps.gif ; cd ..
done
#
#-----------------------------------------------
# Tracé.
#-----------------------------------------------
#
cd $reps
#
#-----------------------------------------------
# Extrêmes de tracé.
#-----------------------------------------------
#
if [ "$champ" = "VVV1" ] ; then
	#
	#-----------------------------------------------
	# Extrêmes en dur.
	#-----------------------------------------------
	#
	trace_min=-3.30
	trace_max=3.30
elif [ "$champ" = "VOM1" ] ; then
	#
	#-----------------------------------------------
	# Extrêmes en dur.
	#-----------------------------------------------
	#
	trace_min=-0.06
	trace_max=0.06
elif [ "$champ" = "VKK1" ] ; then
	#
	#-----------------------------------------------
	# Extrêmes en dur.
	#-----------------------------------------------
	#
	trace_min=0.
	trace_max=84.
else
	#
	#-----------------------------------------------
	# Extrêmes calculés à partir des données:
	# ils seront (moyenne - 3*ect) et (moyenne + 3*ect)
	#-----------------------------------------------
	#
	cat *$champ*.dta > $champ.total
	minm -o $champ.total > $champ.total.extremes
	moy_3eme_colonne=`extl $champ.total.extremes 15`
	ect_3eme_colonne=`extl $champ.total.extremes 16`
	trace_min=`cals "$moy_3eme_colonne $ect_3eme_colonne 3 * -"`
	trace_max=`cals "$moy_3eme_colonne $ect_3eme_colonne 3 * +"`
fi
#
#-----------------------------------------------
# Conversion de ces extrêmes en une palette de couleurs UNIRAS.
#-----------------------------------------------
#
couu $trace_min $trace_max -0
#
#-----------------------------------------------
# Conversion fichiers "DD" en fichiers EPS.
#-----------------------------------------------
#
dd2eps *$champ*.doc
#
#-----------------------------------------------
# Conversion des EPS en GIF.
#-----------------------------------------------
#
convertp gif *$champ*.eps
#
#-----------------------------------------------
# Animation.
#-----------------------------------------------
#
xanim *$champ*.gif &
