#!/bin/bash
# --------------------------------------------------------------
# 
# --------------------------------------------------------------
# Sujet:
# Methode:
# Externes:
# Auteur:   2003-12, J.M. Piriou.
# Modifications:
# --------------------------------------------------------------
# En entrée:
# En sortie:
# --------------------------------------------------------------
proc=$(basename $0) # nom de la présente procédure.
pref=`tempo`/$proc.$RANDOM # préfixe des fichiers temporaires.
dirloc=`pwd` # chemin du répertoire local.
#
#-----------------------------------------------
# Traitement de la ligne de commande.
#-----------------------------------------------
#
if [ $# -eq 2 ]
then
	#
	# Nombre d'arguments OK.
	#
	aaaa=$1
	mm=$2
	fimpact="gogoldegogol"
elif [ $# -eq 3 ]
then
	#
	# Nombre d'arguments OK.
	#
	aaaa=$1
	mm=$2
	fimpact=$3
else
	#
	# Mauvais nombre d'arguments.
	#
	echo " "
	echo "OBJET: tendances en 72h des DDH mensuels moins la tendance entre les analyses."
	echo " "
	echo "UTILISATION: $proc ANNEE MOIS [FICDDHIMPACT]"
	echo " "
	echo "	Le fichier FICDDHIMPACT est optionnel."
	echo "	Si on le fournit, ce fichier sera tracé aux mêmes"
	echo "	palettes de couleur que ceux issus de la chaîne opérationnelle"
	echo "	de l'année ANNEE et mois MOIS."
	echo "	Ce fichier sera le plus souvent fourni comme la différence"
	echo "	entre une prévision expérience "
	echo "	et une prévision expérience."
	echo " "
	echo "METHODE: "
	echo " "
	echo "EXEMPLE: $proc 2003 06"
	echo " "
	exit
fi
fdate0=$aaaa.$mm
#
#-----------------------------------------------
# Monochrome ou couleur?
#-----------------------------------------------
#
llchrome=" " # couleur.
llchrome="-mono" # noir et blanc.
#
#-----------------------------------------------
# Création du répertoire de sortie s'il n'existe pas.
#-----------------------------------------------
#
reps=$dirloc/$proc.res
if test ! -d $reps
then
	mkdir $reps
fi
#
#-----------------------------------------------
# Fichier des tendances en 72h, moyen sur un mois.
#-----------------------------------------------
#
echo "Fichier des tendances en 72h, moyen sur un mois"
f72=$reps/$fdate0.f72
if test ! -s $f72
then
	f72_jmp=`basejmp`/ch/ddh/dta_sauveg/oper/cumuls_mensuels/$aaaa/$mm/dhfzoprod+0072.r0.lfa
	if test -s $f72_jmp
	then
		#
		#-----------------------------------------------
		# Le fichier existe sur la base de données JMP.
		#-----------------------------------------------
		#
		cp $f72_jmp $f72
	else
		#
		#-----------------------------------------------
		# Le fichier n'existe pas sur la base de données JMP.
		# On va le chercher sur archive.
		#-----------------------------------------------
		#
		ftgetp /chaine/mxpt/mxpt001/ddh/oper/$aaaa/$mm/dhfzoprod+0072.r0 $f72
	fi
fi
#
#-----------------------------------------------
# Test d'existence du fichier avant de continuer le travail.
#-----------------------------------------------
#
ftest=$f72
if test ! -s $ftest
then
	echo " "
	echo "$proc/ERREUR: le fichier $ftest est absent!..."
	echo " "
	exit
fi
#
#-----------------------------------------------
# Fichier-analyse du 1er du mois de MM.
#-----------------------------------------------
#
echo "Fichier-analyse du 1er du mois de MM"
fmm0=$reps/$fdate0.dhfzoarpe+0006
if test ! -s $fmm0
then
	ftgetp /chaine/mxpt/mxpt001/arpege/oper/assim/$aaaa/$mm/01/r0/dhfzoarpe+0006 $fmm0
fi
#
#-----------------------------------------------
# Fichier-analyse du 1er du mois de MM+1.
#-----------------------------------------------
#
echo "Fichier-analyse du 1er du mois de MM+1"
mm1=`cals -fi2.2 "$mm 1 +"`
fdate1=$aaaa.$mm1
fmm1=$reps/$fdate1.dhfzoarpe+0006
if test ! -s $fmm1
then
	ftgetp /chaine/mxpt/mxpt001/arpege/oper/assim/$aaaa/$mm1/01/r0/dhfzoarpe+0006 $fmm1
fi
#
#-----------------------------------------------
# Test d'existence du fichier avant de continuer le travail.
#-----------------------------------------------
#
ftest=$fmm1
if test ! -s $ftest
then
	echo " "
	echo "$proc/ERREUR: le fichier $ftest est absent!..."
	echo " "
	exit
fi
#
#-----------------------------------------------
# On va dans le répertoire de sortie.
#-----------------------------------------------
#
cd $reps
#
#-----------------------------------------------
# Différence entre (1er du mois de MM+1) et (1er du mois de MM).
#-----------------------------------------------
#
echo "Différence entre (1er du mois de MM+1) et (1er du mois de MM)"
fdiff_ana=$fdate1-$fdate0.dhfzoarpe+0006
ddh- $fmm1 $fmm0 $fdiff_ana
#
#-----------------------------------------------
# Test d'existence du fichier avant de continuer le travail.
#-----------------------------------------------
#
ftest=$fdiff_ana
if test ! -s $ftest
then
	echo " "
	echo "$proc/ERREUR: le fichier $ftest est absent!..."
	echo " "
	exit
fi
#
#-----------------------------------------------
# Liste des champs à traiter.
#-----------------------------------------------
#
cat <<EOF > lc0
VCT0
VQV0
VKK0
EOF
#
#-----------------------------------------------
# Interprétation de la différence.
#-----------------------------------------------
#
echo "Interprétation de la différence"
ddhi -llc0 $fdiff_ana
#
#-----------------------------------------------
# Nb de jours entre (1er du mois de MM+1) et (1er du mois de MM).
#-----------------------------------------------
#
echo "Nb de jours entre (1er du mois de MM+1) et (1er du mois de MM)"
date0=`ddhr -bs $fmm0`
date1=`ddhr -bs $fmm1`
ecart=`cals -fi4 "$date0 $date1 ddays"`
echo "$proc: nombre de jours = $ecart"
#
#-----------------------------------------------
# On divise par le nb de jours.
#-----------------------------------------------
#
echo "On divise par le nb de jours"
for f in $fdiff_ana*0.dta
do
	cat <<EOF> tmp.calf.nam
	&NAMCALF
	   clent(1)='F1: $f'
	   clent(2)='F2: '
	   clent(3)='F3: '
	   clent(4)='F4: '
	   clent(5)='F5: '
	   clent(6)='F6: '
	   clent(7)='F7: '
	   clent(8)='F8: '
	   clent(9)='F9: '
	   clop1='C1: c11'
	   clop2='C2: c12'
	   clop3='C3: c13 $ecart /'
	   clop4='C4: '
	   clop5='C5: '
	   clop6='C6: '
	   clop7='C7: '
	   clop8='C8: '
	   clop9='C9: '
	   clficout='$f.sor'
	   clformat='(9g16.7)'
	&END
EOF
	calf tmp.calf.nam ; rm tmp.calf.nam
	mv $f.sor $f
done # fin de boucle sur .
#
#-----------------------------------------------
# On change l'unité; ex: K devient K/jour.
#-----------------------------------------------
#
echo "On change l'unité; ex: K devient K/jour"
for f in *.doc
do
	grep "UNITE=" $f > funite
	unite=`cat funite`
	unite="$unite/jour"
	echo $unite >> $f
done # fin de boucle sur .
#
#-----------------------------------------------
# Boucle sur les champs DDH à tracer.
#-----------------------------------------------
#
for champ in `cat lc0`
do
	if [ "$champ" = "VCT0" ] ; then
		couu -0.7 0.7 -i0.05 -0
		champ_tend="VCTM"
		titre="TEMPERATURE"
	elif [ "$champ" = "VQV0" ] ; then
		couu -0.1 .1 -0
		champ_tend="VQVM"
		titre="HUMIDITE SPECIFIQUE"
	elif [ "$champ" = "VKK0" ] ; then
		couu -1 1 -0
		champ_tend="VKKM"
		titre="ENERGIE CINETIQUE"
	else
		echo " "
		echo "$proc/ERREUR: champ inconnu: $champ!..."
		echo " "
		exit
	fi
	#
	#-----------------------------------------------
	# Tracé de la différence des analyses.
	#-----------------------------------------------
	#
	echo "Tracé de la différence des analyses"
	echo "#TITRE=$titre : tend. des analyses" >> $fdiff_ana*$champ.doc
	fdoc_diff_ana=`ls $fdiff_ana*$champ.doc`
	fdta_diff_ana=`ls $fdiff_ana*$champ.dta`
	dd2eps $llchrome $fdoc_diff_ana
	#v $fdoc_diff_ana.eps
	#
	#-----------------------------------------------
	# Tracé des tendances en 72h.
	#-----------------------------------------------
	#
	echo "Tracé des tendances en 72h"
	echo $champ_tend > lcm
	ddhi -llcm $f72
	fdoc_f72=`ls $f72*$champ_tend.doc`
	fdta_f72=`ls $f72*$champ_tend.dta`
	echo "#TITRE=$titre : tend. en 72h" >> $fdoc_f72
	dd2eps $llchrome $fdoc_f72
	#v $fdoc_f72.eps
	#
	#-----------------------------------------------
	# Différence (p72h moyennes) - (tendance entre analyses).
	#-----------------------------------------------
	#
	echo "Tracé des tendances en 72h corrigées des tendances des analyses"
	fdta_biais=$fdate0.$champ_tend.biais.dta
	rm -f $fdta_biais
	cat <<EOF> tmp.calf.nam
	&NAMCALF
	   clent(1)='F1: $fdta_diff_ana'
	   clent(2)='F2: $fdta_f72'
	   clent(3)='F3: '
	   clent(4)='F4: '
	   clent(5)='F5: '
	   clent(6)='F6: '
	   clent(7)='F7: '
	   clent(8)='F8: '
	   clent(9)='F9: '
	   clop1='C1: c11'
	   clop2='C2: c12'
	   clop3='C3: c23 c13 -'
	   clop4='C4: '
	   clop5='C5: '
	   clop6='C6: '
	   clop7='C7: '
	   clop8='C8: '
	   clop9='C9: '
	   clficout='$fdta_biais'
	   clformat='(9g16.7)'
	&END
EOF
	calf tmp.calf.nam ; rm tmp.calf.nam
	#
	#-----------------------------------------------
	# Test d'existence du fichier avant de continuer le travail.
	#-----------------------------------------------
	#
	ftest=$fdta_biais
	if test ! -s $ftest
	then
		echo " "
		echo "$proc/ERREUR: le fichier $ftest est absent!..."
		echo " "
		exit
	fi
	fdoc_biais=$fdta_biais.doc
	cp $fdoc_f72 $fdoc_biais
	echo "#TITRE=$titre : tend. en 72h - tend. analyses" >> $fdoc_biais
	echo "#FICHIER=$fdta_biais" >> $fdoc_biais
	dd2eps $llchrome $fdoc_biais
	#v $fdoc_biais.eps
	#
	#-----------------------------------------------
	# Tracé de l'impact.
	#-----------------------------------------------
	#
	if test -s ../$fimpact
	then
		echo "Tracé de l'impact"
		cp ../$fimpact $fimpact
		echo $champ_tend > lcm
		ddhi -llcm $fimpact
		fdoc_impact=`ls $fimpact*$champ_tend.doc`
		fdta_impact=`ls $fimpact*$champ_tend.dta`
		echo "#TITRE=$titre : impact modif. phys." >> $fdoc_impact
		dd2eps $llchrome $fdoc_impact
		#v $fdoc_impact.eps
	fi
	#
	#-----------------------------------------------
	# Conversion EPS > PPM.
	#-----------------------------------------------
	#
	echo "Conversion EPS > JPG"
	if test -s ../$fimpact
	then
		convertp ppm $fdoc_diff_ana.eps $fdoc_f72.eps $fdoc_biais.eps $fdoc_impact.eps
	else
		convertp ppm $fdoc_diff_ana.eps $fdoc_f72.eps $fdoc_biais.eps
	fi
	#
	#-----------------------------------------------
	# Anamorphose des images PPM.
	#-----------------------------------------------
	#
	echo "Anamorphose des images"
	taillex=600 # taille de sortie.
	tailley=`cals -fi4 "$taillex 0.706 *"` # Le rapport d'aspect des DDH est environ Y/X=0.706.
	if test -s ../$fimpact
	then
		liste_ppm="$fdoc_diff_ana.ppm $fdoc_f72.ppm $fdoc_biais.ppm $fdoc_impact.ppm"
	else
		liste_ppm="$fdoc_diff_ana.ppm $fdoc_f72.ppm $fdoc_biais.ppm"
	fi
	for fppm in $liste_ppm
	do
		imgana $fppm -x$taillex -y$tailley $fppm.ana
	done # fin de boucle sur .
	if test -s ../$fimpact
	then
		#
		#-----------------------------------------------
		# Mise des 4 images PPM en une JPG.
		#-----------------------------------------------
		#
		taillex1=`cals -fi4 "$taillex 1 +"`
		tailley1=`cals -fi4 "$tailley 1 +"`
		f4res_jpg=$fdate0.$fimpact.$champ_tend.jpg
		imgjux $fdoc_diff_ana.ppm.ana 1 1 \
			$fdoc_f72.ppm.ana $taillex1 1 \
			$fdoc_biais.ppm.ana 1 $tailley1 \
			$fdoc_impact.ppm.ana $taillex1 $tailley1 \
			$f4res_jpg
		v $f4res_jpg
		#
		#-----------------------------------------------
		# Mise des 4 images EPS en une PS.
		#-----------------------------------------------
		#
		f4res_ps=$fdate0.$fimpact.$champ_tend.ps
		2ps $fdoc_diff_ana.eps $fdoc_f72.eps $fdoc_biais.eps $fdoc_impact.eps $f4res_ps
	else
		#
		#-----------------------------------------------
		# Mise des 3 images PPM en une JPG.
		#-----------------------------------------------
		#
		taillex1=`cals -fi4 "$taillex 1 +"`
		tailley1=`cals -fi4 "$tailley 1 +"`
		f3res_jpg=$fdate0.$champ_tend.jpg
		imgjux $fdoc_diff_ana.ppm.ana 1 1 \
			$fdoc_f72.ppm.ana $taillex1 1 \
			$fdoc_biais.ppm.ana 1 $tailley1 \
			$f3res_jpg
		v $f3res_jpg
		#
		#-----------------------------------------------
		# Mise des 3 images EPS en une PS.
		#-----------------------------------------------
		#
		f3res_ps=$fdate0.$champ_tend.ps
		2ps $fdoc_diff_ana.eps $fdoc_f72.eps $fdoc_biais.eps $f3res_ps
	fi
done # fin de boucle sur .
#
#-----------------------------------------------
# Nettoyage.
#-----------------------------------------------
#
rm -f $pref*
