#!/bin/bash
# --------------------------------------------------------------
# 
# --------------------------------------------------------------
# Sujet:
# Methode:
# Externes:
# Auteur:   2015-06, J.M. Piriou.
# Modifications:
# --------------------------------------------------------------
# En entrée:
# En sortie:
# --------------------------------------------------------------
proc=$(basename $0) # nom de la présente procédure.
pref=`tempo`/$proc.$RANDOM # préfixe des fichiers temporaires.
dirloc=`pwd` # chemin du répertoire local.
set -evx
#
#-----------------------------------------------
# Traitement de la ligne de commande.
#-----------------------------------------------
#
if [ $# -ne 2 ]
then
  #
  # Mauvais nombre d'arguments.
  #
  echo " "
  echo "OBJET: Tracé du bilan de T, qv, et des profils, de fichiers DDH domaines limités. Le bilan est chaque fois effectué entre 2 fichiers de DDH successifs, éventuellement distants d'un seul pas de temps."
  echo " "
  echo "UTILISATION: $proc REPDDH REPS"
  echo "  où REPDDH est le répertoire contenant les fichiers de DDH domaines limités."
  echo "     REPS est le répertoire de sortie recevant les tracés."
  echo " "
  exit
else
  #
  # Nombre d'arguments OK.
  #
  repddh=$1
  reps=$2
fi
#
#-----------------------------------------------
# Création du répertoire de sortie.
#-----------------------------------------------
#
mkdir -p $reps
#
#-------------------------------------------------
# .
#-------------------------------------------------
#
for fddh in $repddh/DHFDL????+????
do
  base=`basename $fddh`
  cp $fddh $reps/$base.lfa
done
cd $reps
#
#-------------------------------------------------
# Profils finaux.
#-------------------------------------------------
#
fprec="gol"
for fddh in *.lfa
do
  #
  #-------------------------------------------------
  # Extraction du domaine 1.
  #-------------------------------------------------
  #
  fs=$fddh.dom1
  ddht -cEXTRAIT_DOMAIN -1$fddh -s$fs -E1
  fe=$fs
  #
  #-------------------------------------------------
  # Fichier différence entre un pdt donné et le précédent.
  #-------------------------------------------------
  #
  if [ "$fprec" = "gol" ] ; then
    echo "Premier fichier"
  else
    ddht -cDIFFE_EC2_EC1 -2$fe -1$fprec -s$fprec.diff
  fi
  fprec=$fe
done
#
#-------------------------------------------------
# Bilan de T à chaque pdt.
#-------------------------------------------------
#
for fddh in *.diff
do
  #
  #-------------------------------------------------
  # Tracé du profil.
  #-------------------------------------------------
  #
  fe=$fddh
  ddh2scm $fe
  ms $fe.Dom001.Var_ini.scm
  dd2gr $fe.Dom001.Var_ini.scm.ms.tmp.theta.doc $fe.Dom001.Var_ini.scm.ms.tmp.theta.doc.svg
  convert $fe.Dom001.Var_ini.scm.ms.tmp.theta.doc.svg $fe.Dom001.Var_ini.scm.ms.tmp.theta.doc.svg.png
  ms $fe.Dom001.Var_fin.scm
  dd2gr $fe.Dom001.Var_fin.scm.ms.tmp.theta.doc $fe.Dom001.Var_fin.scm.ms.tmp.theta.doc.svg
  convert $fe.Dom001.Var_fin.scm.ms.tmp.theta.doc.svg $fe.Dom001.Var_fin.scm.ms.tmp.theta.doc.svg.png
  #
  #-----------------------------------------------
  # Profils de QL QI QR QS CL CI CR CS.
  #-----------------------------------------------
  #
  cat <<EOF >lc
VQL1
VQI1
VQR1
VQS1
VCL1
VCI1
VCR1
VCS1
EOF
  ddhi -llc $fddh
  #
  #-----------------------------------------------
  # Tracé.
  #-----------------------------------------------
  #
  run=`ddhr -i $fddh`
  pdt=`mot -43 2 $fddh` # 0200
  fdoc="$fddh.condensats.doc"
  cat <<EOF >$fdoc
#FORMAT=YVI                                                                                      
#TITRE=Condensats
#DATE=
#UNITE=
#LEGENDE_X=q* (g/kg)
#LEGENDE_Y=p (hPa)
#ORIGINE=Prévision $run, instant n°$pdt

#YX=5.

#CHAMP=VQL1
#FICHIER=$fddh.tmp.VQL1.dta

#CHAMP=VQI1
#FICHIER=$fddh.tmp.VQI1.dta

#CHAMP=VQR1
#FICHIER=$fddh.tmp.VQR1.dta

#CHAMP=VQS1
#FICHIER=$fddh.tmp.VQS1.dta

#CHAMP=VCL1
#FICHIER=$fddh.tmp.VCL1.dta

#CHAMP=VCI1
#FICHIER=$fddh.tmp.VCI1.dta

#CHAMP=VCR1
#FICHIER=$fddh.tmp.VCR1.dta

#CHAMP=VCS1
#FICHIER=$fddh.tmp.VCS1.dta
EOF
  dd2png $fdoc $fdoc.png
  #
  #-----------------------------------------------
  # Flux de RR.
  #-----------------------------------------------
  #
  cat <<EOF >lc
FQTPRECISTL
FQTPRECISTN
FQTPRECICOL
FQTPRECICON
FQVTURQNEGAT
FQVCQNG
FQRPL
FQSPN
FCRSEDIM
FCSSEDIM
EOF
  #
  # Le pdt est de 240s. Les flux sont en mm/240s. Pour les avoir en mm/h il faut multiplier par 3600/240=15. ==> -m15.
  # Les flux sont en mm/h. ==> -m1.
  ddhi -cNON -llc -m1. -1VP $fddh
  #
  #-----------------------------------------------
  # Tracé.
  #-----------------------------------------------
  #
  run=`ddhr -i $fddh`
  pdt=`mot -43 2 $fddh` # 0200
  fdoc="$fddh.rr.doc"
  cat <<EOF >$fdoc
#FORMAT=YVI                                                                                      
#TITRE=Précipitations, $run
#DATE=
#UNITE=
#LEGENDE_X=rr (mm/h)
#LEGENDE_Y=z (km)
#ORIGINE=Prévision $run, instant n°$pdt
#YX=5.

  #CHAMP=FQVTURQNEGAT
  #FICHIER=$fddh.tmp.FQVTURQNEGAT.dta
#CHAMP=FQVCQNG
#FICHIER=$fddh.tmp.FQVCQNG.dta

  #CHAMP=FQTPRECISTL
  #FICHIER=$fddh.tmp.FQTPRECISTL.dta
#CHAMP=FQRPL
#FICHIER=$fddh.tmp.FQRPL.dta

  #CHAMP=FQTPRECISTN
  #FICHIER=$fddh.tmp.FQTPRECISTN.dta
#CHAMP=FQSPN
#FICHIER=$fddh.tmp.FQSPN.dta

  #CHAMP=FQTPRECICOL
  #FICHIER=$fddh.tmp.FQTPRECICOL.dta
#CHAMP=FCRSEDIM
#FICHIER=$fddh.tmp.FCRSEDIM.dta

  #CHAMP=FQTPRECICON
  #FICHIER=$fddh.tmp.FQTPRECICON.dta
#CHAMP=FCSSEDIM
#FICHIER=$fddh.tmp.FCSSEDIM.dta
EOF
  dd2png $fdoc $fdoc.png
  #
  #-------------------------------------------------
  # Bilan sur un pas de temps.
  #-------------------------------------------------
  #
  for champ in QV QI CI
  do
    ddhb -v pcmt/$champ -i $fe
    indice=`ddhr -i $fe`
    cp zddhb.$champ.$indice.graph.doc.svg $fe.bilan.$champ.svg
    convert $fe.bilan.$champ.svg $fe.bilan.$champ.svg.png
  done # champ
  #
  #-------------------------------------------------
  # Combinaison des 4 images en 1.
  #-------------------------------------------------
  #
  imgcomb -x 3 $fe.combinee.png \
    $fe.Dom001.Var_fin.scm.ms.tmp.theta.doc.svg.png \
    $fddh.condensats.doc.png \
    $fddh.rr.doc.png \
    $fe.bilan.QV.svg.png \
    $fe.bilan.QI.svg.png \
    $fe.bilan.CI.svg.png
  v $fe.combinee.png
done # fddh
