#!/bin/bash
# --------------------------------------------------------------
# 
# --------------------------------------------------------------
# Sujet:
# Methode:
# Externes:
# Auteur:   2016-02, J.M. Piriou.
# Modifications:
# --------------------------------------------------------------
# En entrée:
# En sortie:
# --------------------------------------------------------------
proc=$(basename $0) # nom de la présente procédure.
pref=`tempo`/$proc.$RANDOM # préfixe des fichiers temporaires.
dirloc=`pwd` # chemin du répertoire local.
set -x
#
#-----------------------------------------------
# Traitement de la ligne de commande.
#-----------------------------------------------
#
if [ $# -ne 3 ]
then
  #
  # Mauvais nombre d'arguments.
  #
  echo " "
  echo "OBJET: Tracé du bilan de T, qv, et des profils, de fichiers DDH domaines limités. Le bilan est chaque fois effectué entre 2 fichiers de DDH successifs, éventuellement distants d'un seul pas de temps."
  echo " "
  echo "UTILISATION: $proc REPDDH NIV REPS"
  echo "  où REPDDH est le répertoire contenant les fichiers de DDH domaines limités."
  echo "     NIV est le niveau à extraire."
  echo "     REPS est le répertoire de sortie recevant les tracés."
  echo " "
  exit
else
  #
  # Nombre d'arguments OK.
  #
  repddh=$1
  niv=$2
  reps=$3
fi
#
#-----------------------------------------------
# Création du répertoire de sortie.
#-----------------------------------------------
#
reps=`nomc $reps`
mkdir -p $reps
#
#-------------------------------------------------
# .
#-------------------------------------------------
#
for fddh in $repddh/DHFDL*
do
  base=`basename $fddh`
  cp $fddh $reps/$base.lfa
done
cd $reps
#
#-------------------------------------------------
# Profils finaux.
#-------------------------------------------------
#
fprec="gol"
for fddh in *.lfa
do
  #
  #-------------------------------------------------
  # Extraction du domaine 1.
  #-------------------------------------------------
  #
  fs=$fddh.dom1
  ddht -cEXTRAIT_DOMAIN -1$fddh -s$fs -E1
  ddht -cEXTRAIT_NIVEAUX -1$fs -stotogol -E$niv
  mv totogol $fs
  fe=$fs
  #
  #-------------------------------------------------
  # Fichier différence entre un pdt donné et le précédent.
  #-------------------------------------------------
  #
  if [ "$fprec" = "gol" ] ; then
    echo "Premier fichier"
  else
    ddht -cDIFFE_EC2_EC1 -2$fe -1$fprec -s$fprec.diff
  fi
  fprec=$fe
done
#
#-------------------------------------------------
# Bilan de T à chaque pdt.
#-------------------------------------------------
#
champs="CT QV"

for fddh in *.diff
do
  #
  #-------------------------------------------------
  # Bilan sur un pas de temps.
  #-------------------------------------------------
  #
  for champ in $champs
  do
    export DDH_PLOT=""
    ddhb -v oper/$champ -i $fddh
    indice=`ddhr -i $fddh`
    for fdta in $fddh.ddhb.oper/$champ.tmp/budget.oper/*.dta
    do
      cp $fdta .
    done
  done
done
#
#-------------------------------------------------
# A partir de n fichiers on créé un seul fichier-évolution temporelle .
#-------------------------------------------------
#
rm -f *.evol
for champ in $champs
do
  for fdta in  $champ.*.diff.*.dta
  do
    poste_bilan=`mot 7 -2 $fdta`
    cat $fdta >> $champ.$poste_bilan.evol
  done
  fdoc=$indice.$champ.niv$niv.bilan.doc
  dta2dd $fdoc $champ.*.evol
  cat <<EOF >> $fdoc
#TITRE=Bilan de $champ, expérience $indice, niveau $niv
#LEGENDE_X=temps
EOF
  v $fdoc
done
