#!/bin/bash
# --------------------------------------------------------------
# 
# --------------------------------------------------------------
# Sujet:
# Methode:
# Externes:
# Auteur:   2003-11, J.M. Piriou.
# Modifications:
# --------------------------------------------------------------
# En entrée:
# En sortie:
# --------------------------------------------------------------
proc=$(basename $0) # nom de la présente procédure.
pref=`tempo`/$proc.$RANDOM # préfixe des fichiers temporaires.
dirloc=`pwd` # chemin du répertoire local.
#
#-----------------------------------------------
# Exécution.
#-----------------------------------------------
#
echo " "
echo "-----------------------------------------------"
for f in *f90
do
	grep -i "implicit none" $f > $pref.grep
	if test -s $pref.grep
	then
		echo "$f OK" > /dev/null
	else
		echo "$f"
	fi
done # fin de boucle sur .
