#!/bin/bash
# --------------------------------------------------------------
# 
# --------------------------------------------------------------
# Sujet:
# Methode:
# Externes:
# Auteur:   2015-06, J.M. Piriou.
# Modifications:
# --------------------------------------------------------------
# En entrée:
# En sortie:
# --------------------------------------------------------------
proc=$(basename $0) # nom de la présente procédure.
pref=`tempo`/$proc.$RANDOM # préfixe des fichiers temporaires.
dirloc=`pwd` # chemin du répertoire local.
#
#-------------------------------------------------
# .
#-------------------------------------------------
#
set -evx
#
#-----------------------------------------------
# Nettoyage préalable.
#-----------------------------------------------
#
net
install
vu
#
#-----------------------------------------------
# Choix modèle et champs.
#-----------------------------------------------
#
fref=DHFDLAROM+0020.lfa ; diag_type="AROME" ; champs="CT QV KK QL QI" # AROME.
fref=DZ.lfa ; diag_type="oper" ; champs="CT QV KK" # ARPEGE.
fref=DZ.lfa ; diag_type="oper" ; champs="CT" # ARPEGE.
#
#-----------------------------------------------
# Exécution.
#-----------------------------------------------
#
ddhmh $fref $fref.mh
run=`ddhr -i $fref`
for champ in $champs
do
  #
  #-----------------------------------------------
  # Tend.
  #-----------------------------------------------
  #
  cp $fref.mh $fref.mh.lulu.tmp.tend.lfa
  ddhb -v $diag_type/$champ -i $fref.mh.lulu.tmp.tend.lfa > lulu.tmp.tend.tmp.log 2>&1 
  convert zddhb.$champ.$run.graph.doc.svg lulu.tmp.tend.png
  rm zddhb.$champ.$run.graph.doc.svg 
  #
  #-----------------------------------------------
  # Flux.
  #-----------------------------------------------
  #
  cp $fref.mh $fref.mh.lulu.tmp.flux.lfa
  ddhb -v $diag_type/$champ -i $fref.mh.lulu.tmp.flux.lfa -c flux > lulu.tmp.flux.tmp.log 2>&1 
  rm -f lulu.tmp.flux.png
  convert zddhb.$champ.$run.graph.doc.svg lulu.tmp.flux.png
  rm zddhb.$champ.$run.graph.doc.svg 
  #
  #-----------------------------------------------
  # Tracé.
  #-----------------------------------------------
  #
  imgcomb -x 2 2.$champ.png lulu.tmp.tend.png lulu.tmp.flux.png 
  v 2.$champ.png
done # champ.
