#!/bin/bash
# --------------------------------------------------------------
# 
# --------------------------------------------------------------
# Sujet:
# Methode:
# Externes:
# Auteur:   2024-02-12, J.M. Piriou.
# Modifications:
# --------------------------------------------------------------
# En entrée:
# En sortie:
# --------------------------------------------------------------
proc=$(basename $0) # nom de la présente procédure.
pref=`tempo`/$proc.$RANDOM # préfixe des fichiers temporaires.
dirloc=`pwd` # chemin du répertoire local.
set -evx
#
#-------------------------------------------------
# .
#-------------------------------------------------
#
fddh="DHFZOFCST+0225_GSJ4_PCMT.lfa"
ddhmh $fddh $fddh.mh
for champ in CT QV QL QI QR QS CL CI CR CS
do
  pre="$fddh.mh.$champ.tmp"
  ddhb -v pcmt/$champ -i $fddh.mh -o $pre.svg
  convert $pre.svg $pre.png
  v $pre.png
done
