#!/bin/bash                                                                                      
# --------------------------------------------------------------
# 
# --------------------------------------------------------------
# Sujet:
# Methode:
# Externes:
# Auteur:   2023-10-17, J.M. Piriou.
# Modifications:
# --------------------------------------------------------------
# En entrée:
# En sortie:
# --------------------------------------------------------------
proc=$(basename $0) # nom de la présente procédure.
pref=`tempo`/$proc.$RANDOM # préfixe des fichiers temporaires.
dirloc=`pwd` # chemin du répertoire local.
#
#-------------------------------------------------
# .
#-------------------------------------------------
#
if [ "`hostname`" = "sxproc1" ] ; then
  v $*
else
  eog $* &
fi
