#!/bin/bash
# --------------------------------------------------------------
# 
# --------------------------------------------------------------
# Sujet:
# Methode:
# Externes:
# Auteur:   2024-03, J.M. Piriou.
# Modifications:
# --------------------------------------------------------------
# En entrée:
# En sortie:
# --------------------------------------------------------------
proc=$(basename $0) # nom de la présente procédure.
pref=`tempo`/$proc.$RANDOM # préfixe des fichiers temporaires.
dirloc=`pwd` # chemin du répertoire local.
set -evx
#
#-----------------------------------------------
# Exécution.
#-----------------------------------------------
#
cd ../data
net
rm -f *.ref.*
#
#-----------------------------------------------
# Validation de ddht -cDIFFE_EC2_EC1 sur un fichier DDH AROME.
#-----------------------------------------------
#
f1="20240122.G72E.DHFDLFCST+0027.SIRTA.lfa"
f2="20240122.G72E.DHFDLFCST+0028.SIRTA.lfa"
fref="20240122.G72E.DHFDLFCST+0027-0028.SIRTA.lfa.ref"
../ddht -cDIFFE_EC2_EC1 -2$f2 -1$f1 -s$fref.tmp
if test -s $fref
then
  lfaminm $fref > $fref.minm
  lfaminm $fref.tmp > $fref.tmp.minm
  diff $fref.minm $fref.tmp.minm > $fref.tmp.minm.diff
  if test -s $fref.tmp.minm.diff
  then
    cat $fref.tmp.minm.diff
    exit
  fi
  lfadiffrelnz $fref $fref.tmp > $fref.diff 2>&1
  if test -s $fref.diff
  then
    cat $fref.diff
    exit
  fi
else
  mv $fref.tmp $fref 
fi
#
#-----------------------------------------------
# Validation de ddht -cDIFFE_EC2_EC1 sur un fichier DDH ARPEGE.
#-----------------------------------------------
#
f1="DHFZOOPER+0048.20240318.lfa"
f2="DHFZOOPER+0072.20240318.lfa"
fref="DHFZOOPER+0072-0048.20240318.lfa.ref"
../ddht -cDIFFE_EC2_EC1 -2$f2 -1$f1 -s$fref.tmp
if test -s $fref
then
  lfaminm $fref > $fref.minm
  lfaminm $fref.tmp > $fref.tmp.minm
  diff $fref.minm $fref.tmp.minm > $fref.tmp.minm.diff
  if test -s $fref.tmp.minm.diff
  then
    cat $fref.tmp.minm.diff
    exit
  fi
  lfadiffrelnz $fref $fref.tmp > $fref.diff 2>&1
  if test -s $fref.diff
  then
    cat $fref.diff
    exit
  fi
else
  mv $fref.tmp $fref 
fi
