#!/bin/bash
# --------------------------------------------------------------
# 
# --------------------------------------------------------------
# Sujet:
# Methode:
# Externes:
# Auteur:   2019-11-26, J.M. Piriou.
# Modifications:
# --------------------------------------------------------------
# En entrée:
# En sortie:
# --------------------------------------------------------------
proc=$(basename $0) # nom de la présente procédure.
pref=`tempo`/$proc.$RANDOM # préfixe des fichiers temporaires.
dirloc=`pwd` # chemin du répertoire local.
#
#-----------------------------------------------
# Traitement de la ligne de commande.
#-----------------------------------------------
#
set -evx
#
#-------------------------------------------------
# .
#-------------------------------------------------
#
cd ../data
ddht -cEXTRAIT_DOMAIN -E15 -1DZ.lfa -sDZ_dom15.lfa
ddht -cEXTRAIT_NIVEAUX -E103,104,105 -1DZ_dom15.lfa -sDZ_dom15_niv103-105.lfa
ddht -cEXTRAIT_NIVEAUX -E105 -1DZ_dom15.lfa -sDZ_dom15_niv105.lfa
